language: swift
osx_image: xcode9.4

podfile: NMDb/Podfile

cache: cocoapods

before_install:
  - brew update
  - gem install cocoapods
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-build
 
script:
  - cd NMDb
  - pod install
  - xcodebuild -scheme NMDb -workspace NMDb.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=11.4' build test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
