language: swift # or objective-c
osx_image: xcode9.4
script:
  - cd NMDb
  - xcodebuild -scheme NMDb -workspace NMDb.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=11.4' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
